/**:
  ros__parameters:
    port_name: "/dev/tty_drive_motor_controller"
    enable_debug: true
    wheel_separation: 0.4
    rotational_amplification: 4.0
    wheel_radius: 0.075
    angular_velocity_limit: 1.0
    max_track_acceleration_rad_s2: 6.0
    max_track_deceleration_rad_s2: 16.0
    max_track_jerk_rad_s3: 120.0
    left_velocity_pid.k_p: 4.0
    left_velocity_pid.k_i: 8.0
    left_velocity_pid.k_d: 0.0
    right_velocity_pid.k_p: 4.0
    right_velocity_pid.k_i: 8.0
    right_velocity_pid.k_d: 0.0
    left_position_pid.k_p: 8.0
    left_position_pid.k_i: 0.0
    left_position_pid.k_d: 0.0
    right_position_pid.k_p: 8.0
    right_position_pid.k_i: 0.0
    right_position_pid.k_d: 0.0
    left_velocity_feed_forward.k_v: 0.3
    left_velocity_feed_forward.k_s: 2.0
    left_velocity_feed_forward.k_s_rotational: 3.0
    right_velocity_feed_forward.k_v: 0.3
    right_velocity_feed_forward.k_s: 2.0
    right_velocity_feed_forward.k_s_rotational: 3.0
    invert_forward_direction: true
